[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "reflect"
    version = "@project.version@"
    path = "../reflect-native/build/libs/reflect-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["reflect"]
