[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/config" = "@stdlib.config.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/io" = "@stdlib.io.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "reflect"
    version = "@project.version@"
    path = "../reflect-native/build/libs/reflect-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["reflect"]
